### ISSUE TITLE
Authenticate wont work

### ISSUE THREAD

**Issue by tomkosm** [westphilm/forwardproxy#1]
Hey, i cant get it to work with authenticate turned on.It seems that authenticate consumes .recv data and the headers with them.

**Comment by westphilm** [comment]
Hi thomas510111, thanks for your question. It would be interesting, which error is occured. What means "wont work"?

However, I'm not quite sure about the read buffersize (4096) in line 64. Maybe it is to large or this piece of code ist not optimal. For me it works fine. 

You could put some debug-echo's around the lines 47-50 and 64-69. This code reads the first bytes from clientsocket and extracts username and password from this data. Also you could put some echos around line 143, this code calls the authenticate method.

I will examine this issue on occasion, fix it if I can and write a test-case for it. Let us know, if you have found new details about it. Thanks for yout hint.

**Comment by westphilm** [comment]
Not reproducable.
