### ISSUE TITLE
need your help on project , please .

### ISSUE THREAD

**Issue by ingnelson** [westphilm/forwardproxy#2]
Hello.

I want to create a proxy on python i just code most of the proxy : 

https://github.com/ingnelson/proxy_python_not_finish/blob/master/proxy.py

I want the python proxy on port 80 create the connection between the client (android or PC) and my SSH server on port 442.

The python proxy and the SSH server are running on my VPS Ubuntu.

similar to this : 

![Tunnel1](https://user-images.githubusercontent.com/6626845/86406195-e950cd80-bc6f-11ea-831e-9354405d4ccf.jpg)
![Tunnel2](https://user-images.githubusercontent.com/6626845/86406203-eb1a9100-bc6f-11ea-9db5-0d6d7c572f97.jpg)

but my proxy stop at the connection like this : 

![image](https://user-images.githubusercontent.com/6626845/86963249-6fae5900-c121-11ea-9cc6-fd36b062dddb.png)

can you please check the my proxy , please ?

**Comment by westphilm** [comment]
Hi ingnelson, thanks for your question. But sorry, I have no time to analyze your project or your ssh configuration. The provided details are not enough for a quick fix. Regards, Flo

**Comment by westphilm** [comment]
Additional info: I'm using my ForwardProxy via HTTPS. 
Calling an Apache HTTP Server on public port 0.0.0.0:443, forwarding to ForwardProxy port 127.0.0.1:9899, forwarding to a local HTTP port 127.0.0.1:8081. Works fine for me.
